[project]
name = "astral-led"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.1.0",
    "rgbmatrix",
    "rgbmatrixemulator>=0.11.6",
]

[tool.uv.sources]
rgbmatrix = { git = "https://github.com/chrisgilldc/rpi-rgb-led-matrix" }
